`ExpansionTile` Control
flet-dev/flet pull request #2140
Opened 2023-11-26 16:35 UTC by ndonkoHenri

Close #1719 

`Example code:`
```python
import flet as ft

def main(page: ft.Page):
    page.spacing = 0
    page.theme_mode = ft.ThemeMode.LIGHT
    page.padding = ft.padding.only(top=0)

    def handle_expansion_tile_change(e):
        print(f"ExpansionTile was {'expanded' if e.data=='true' else 'collapsed'}")
        e.control.trailing.name = (
            ft.icons.ARROW_DROP_DOWN
            if e.control.trailing.name == ft.icons.ARROW_DROP_DOWN_CIRCLE
            else ft.icons.ARROW_DROP_DOWN_CIRCLE
        )
        page.update()

    page.add(
        ft.ExpansionTile(
            title=ft.Text("ExpansionTile 1"),
            subtitle=ft.Text("Trailing expansion arrow icon"),
            affinity=ft.TileAffinity.PLATFORM,
            maintain_state=True,
            collapsed_text_color=ft.colors.RED,
            text_color=ft.colors.RED,
            controls=[ft.ListTile(title=ft.Text("This is tile number 1"))],
        ),
        ft.ExpansionTile(
            title=ft.Text("ExpansionTile 2"),
            subtitle=ft.Text("Custom expansion arrow icon"),
            trailing=ft.Icon(ft.icons.ARROW_DROP_DOWN),
            collapsed_text_color=ft.colors.GREEN,
            text_color=ft.colors.GREEN,
            on_change=handle_expansion_tile_change,
            controls=[ft.ListTile(title=ft.Text("This is tile number 2"))],
        ),
        ft.ExpansionTile(
            title=ft.Text("ExpansionTile 3"),
            subtitle=ft.Text("Leading expansion arrow icon"),
            affinity=ft.TileAffinity.LEADING,
            initially_expanded=True,
            collapsed_text_color=ft.colors.BLUE,
            text_color=ft.colors.BLUE,
            controls=[
                ft.ListTile(title=ft.Text("This is tile number 3")),
                ft.ListTile(title=ft.Text("This is tile number 4")),
                ft.ListTile(title=ft.Text("This is tile number 5")),
            ],
        ),
    )

ft.app(target=main)
```

2023-11-27 19:01 UTC, FeodorFitsner requested changes

2023-11-27 19:01 UTC, FeodorFitsner commented on sdk/python/packages/flet-core/src/flet_core/expansion_tile.py
> +        self._set_attr_json("Shape", self.__shape)
`"Shape"` -> `"shape". Let's use `camelCase` for consistency.

2023-11-27 22:20 UTC, ndonkoHenri commented
Made the changes as requested.

2023-11-28 00:18 UTC, FeodorFitsner approved these changes

2023-11-28 00:18 UTC, merged