Text.letter_spacing & Text.line_height property
flet-dev/flet pull request #2574
Opened 2024-02-08 06:52 UTC by ariefendi992

Example code

```
import flet
from flet import Page, Text

def main(page: Page):
    page.window_always_on_top = True
    page.add(
        Text(
            "Hello, world!\nHello Flet",
            letter_spacing=2,
            line_height=4,
        )
    )
    page.update()

flet.app(target=main)
```

2024-02-08 06:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/flet-dev/flet?pullRequest=2574) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/flet-dev/flet?pullRequest=2574) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/flet-dev/flet?pullRequest=2574) it.</sub>

2024-02-08 11:17 UTC, ndonkoHenri requested changes
Thanks for your contribution!
The two properties you added are TextStyle properties - so I suggest we add them to the [`TextStyle` dataclass](https://github.com/ariefendi992/flet/blob/d45ca11c99ff05c9bee70d34ece68f21074e7547/sdk/python/packages/flet-core/src/flet_core/text_style.py#L28) instead.

2024-02-08 17:25 UTC, FeodorFitsner approved these changes

2024-02-08 18:07 UTC, ndonkoHenri commented on package/lib/src/controls/text.dart
> +        letterSpacing: control.attrDouble('letterSpacing', null),
Having it here is unnecessary because `Text` has no more has `letter_spacing` attribute.

2024-02-08 23:27 UTC, ndonkoHenri approved these changes

2024-02-08 23:29 UTC, ndonkoHenri commented
Thanks, @ariefendi992 ! I am merging...
Can you please make a PR [here](https://github.com/flet-dev/website), adding this new property to the `TextStyle` docs?

2024-02-08 23:31 UTC, merged

2024-02-13 14:22 UTC, ariefendi992 commented
yes, i can.